### ISSUE TITLE
More details on working system?

### ISSUE THREAD

**Issue by DrChr** [leath-dub/vboox#1]
Hi,
I'd like to try this on my Ultra tab C, but I'd need some help in setting it up. Would you mind assisting?
One way might be to describe what your (working) system looks like?
I'm guessing you're using some Arch release. And that you tested it with some program, e.g. 'Gimp'?

Alternatively we could see if you can help me to get it working on one of my computers, e.g. my primary laptop is still  doing Ubuntu 20.04.  Maybe that's too old?

**Comment by leath-dub** [comment]
Yeah I am on arch (not btw) x86_64, if you can install [cargo](https://www.rust-lang.org/tools/install) (rust) and adb (android-tools-adb on ubuntu ?) Thats basically all you need bar evdev xorg drivers, I think it should be xserver-xorg-input-evdev package on ubuntu.

> I'm guessing you're using some Arch release. And that you tested it with some program, e.g. 'Gimp'?

If its working correctly it should also work as a mouse, hover will move it and pressing down will register a left click.

The only other thing that would be a hurdle is that The ultra C may have a different digitizer, this is not a problem it just means that I need to see what devices are on your device.

Once you have adb and you plug your tablet in (accept debugging message) you need to run
```
adb shell getevent -si
```
That should show all your devices on the tablet one of them should be a "digitizer", basically if you get to this step send the output in here.

hope this helps !

**Comment by DrChr** [comment]
I've already got `cargo` and `adb`. For reference in case of issues later.
```
$ cargo --version && adb --version
cargo 1.48.0 (65cbdd2dc 2020-10-14)
Android Debug Bridge version 1.0.39
Version 1:8.1.0+r23-5ubuntu2
Installed as /usr/lib/android-sdk/platform-tools/adb
```

I'm also watching the repo. It's late so I'll try some things tomorrow. Right now I'm not managing to get adb to work wirelessly, tomorrow I'll just use a cable...

**Comment by DrChr** [comment]
Oh, I tried building:
```
$ cargo build --release
error: failed to parse manifest at `/home/XXX/repos/vboox/Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
```

Seems my cargo is to old :-(

**Comment by leath-dub** [comment]
> Oh, I tried building:
> 
> ```
> $ cargo build --release
> error: failed to parse manifest at `/home/XXX/repos/vboox/Cargo.toml`
> 
> Caused by:
>   failed to parse the `edition` key
> 
> Caused by:
>   this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
> ```
> 
> Seems my cargo is to old :-(

You can install cargo via this link https://www.rust-lang.org/tools/install that should get you the latest version.

**Comment by leath-dub** [comment]
> I've already got `cargo` and `adb`. For reference in case of issues later.
> 
> ```
> $ cargo --version && adb --version
> cargo 1.48.0 (65cbdd2dc 2020-10-14)
> Android Debug Bridge version 1.0.39
> Version 1:8.1.0+r23-5ubuntu2
> Installed as /usr/lib/android-sdk/platform-tools/adb
> ```
> 
> I'm also watching the repo. It's late so I'll try some things tomorrow. Right now I'm not managing to get adb to work wirelessly, tomorrow I'll just use a cable...

I think you need a cable anyway initially (there is another way with bluetooth I think), at least its the easiest. Here is what I think I followed iirc https://stackoverflow.com/questions/42364380/how-can-i-use-adb-over-wifi

**Comment by DrChr** [comment]
> Once you have adb and you plug your tablet in (accept debugging message) you need to run `adb shell getevent -si`
> 
> That should show all your devices on the tablet one of them should be a "digitizer", basically if you get to this step send the output in here.

I took your command and placed it in a script - maybe it'll make sense to commit at a later stage. (Sometimes it's nice to document how something is done by placing commands in a tiny script).

```
$ cat scripts/list-devices-on-tablet.bash 
#!/usr/bin/env bash
#
# List "devices" in tablet
#
# Prerequisites:
# - E.g. connected to tablet via USB cable
# - Allow debug connection
#
# Reference: Discussion in https://github.com/leath-dub/vboox/issues/1
adb shell getevent -si
```

Running the command, seems like the digitizer is device 5:
```
(base) ~/repos/vboox$ scripts/list-devices-on-tablet.bash 
add device 1: /dev/input/event1
  name:     "onyx-keyboard"
add device 2: /dev/input/event8
  name:     "bengal-idp-snd-card Button Jack"
add device 3: /dev/input/event7
  name:     "bengal-idp-snd-card Headset Jack"
add device 4: /dev/input/event5
  name:     "onyx-misc"
add device 5: /dev/input/event3
  name:     "onyx_emp_Wacom I2C Digitizer"
add device 6: /dev/input/event2
  name:     "sf-keys"
add device 7: /dev/input/event6
  name:     "onyx-hall"
add device 8: /dev/input/event0
  name:     "qpnp_pon"
add device 9: /dev/input/event4
  name:     "pt_mt"
```

**Comment by leath-dub** [comment]
> > Once you have adb and you plug your tablet in (accept debugging message) you need to run `adb shell getevent -si`
> > That should show all your devices on the tablet one of them should be a "digitizer", basically if you get to this step send the output in here.
> 
> I took your command and placed it in a script - maybe it'll make sense to commit at a later stage. (Sometimes it's nice to document how something is done by placing commands in a tiny script).
> 
> ```
> $ cat scripts/list-devices-on-tablet.bash 
> #!/usr/bin/env bash
> #
> # List "devices" in tablet
> #
> # Prerequisites:
> # - E.g. connected to tablet via USB cable
> # - Allow debug connection
> #
> # Reference: Discussion in https://github.com/leath-dub/vboox/issues/1
> adb shell getevent -si
> ```
I agree, admitedly it has been a weekend project so I didn't really document everthing yet, I will be releasing a daemon script (uses setsid) also that allows you to auto start the driver.
> 
> Running the command, seems like the digitizer is device 5:
> 
> ```
> (base) ~/repos/vboox$ scripts/list-devices-on-tablet.bash 
> add device 1: /dev/input/event1
>   name:     "onyx-keyboard"
> add device 2: /dev/input/event8
>   name:     "bengal-idp-snd-card Button Jack"
> add device 3: /dev/input/event7
>   name:     "bengal-idp-snd-card Headset Jack"
> add device 4: /dev/input/event5
>   name:     "onyx-misc"
> add device 5: /dev/input/event3
>   name:     "onyx_emp_Wacom I2C Digitizer"
> add device 6: /dev/input/event2
>   name:     "sf-keys"
> add device 7: /dev/input/event6
>   name:     "onyx-hall"
> add device 8: /dev/input/event0
>   name:     "qpnp_pon"
> add device 9: /dev/input/event4
>   name:     "pt_mt"
> ```
That is great news that is the same digitizer, hopefully this will just work, I will still make a separate class for the device just to make clear for people contributing.

**Comment by DrChr** [comment]
I've installed cargo etc via 'rustup', but building gives this error:

```
cargo build --release

   Compiling vboox v0.1.0 (/home/XXX/repos/vboox)
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src/main.rs:1:12
  |
1 | #![feature(iter_collect_into)]
  |            ^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `vboox` (bin "vboox") due to previous error

```
Suggestion/question: Maybe make the code work with the stable Rust?  (To simplify for people wanting to try).


For completenes, current cargo version etc:
```
$ cargo --version
cargo 1.71.0 (cfd3bbd8f 2023-06-08)
$ rustc --version
rustc 1.71.0 (8ede3aae2 2023-07-12)
```

I should probably mention I've never used Rust (but a bunch of other languages/environments).

**Comment by leath-dub** [comment]
> I've installed cargo etc via 'rustup', but building gives this error:
> 
> ```
> cargo build --release
> 
>    Compiling vboox v0.1.0 (/home/XXX/repos/vboox)
> error[E0554]: `#![feature]` may not be used on the stable release channel
>  --> src/main.rs:1:12
>   |
> 1 | #![feature(iter_collect_into)]
>   |            ^^^^^^^^^^^^^^^^^
> 
> For more information about this error, try `rustc --explain E0554`.
> error: could not compile `vboox` (bin "vboox") due to previous error
> ```
> 
> Suggestion/question: Maybe make the code work with the stable Rust? (To simplify for people wanting to try).
> 
> For completenes, current cargo version etc:
> 
> ```
> $ cargo --version
> cargo 1.71.0 (cfd3bbd8f 2023-06-08)
> $ rustc --version
> rustc 1.71.0 (8ede3aae2 2023-07-12)
> ```
> 
> I should probably mention I've never used Rust (but a bunch of other languages/environments).

That is my bad, I pushed a commit to fix that. I didn't know I was running nightly cargo channel.

**Comment by DrChr** [comment]
> That is my bad, I pushed a commit to fix that. I didn't know I was running nightly cargo channel.

Oh, no worries - it's a weekend a project, I understand completely!

It builds now.

**Comment by DrChr** [comment]
I got it to work - cool. Well done creating the driver!
![20230802_112142](https://github.com/leath-dub/vboox/assets/5725271/00c26f5d-f9e4-4e86-b1bb-003a60a0c856)

Has some UX issues, but promising!

**Comment by leath-dub** [comment]
> I got it to work. ![20230802_112142](https://user-images.githubusercontent.com/5725271/257769958-00c26f5d-f9e4-4e86-b1bb-003a60a0c856.jpg)

Awesome !, I will do up a commit this evening and update the readme. I think my suspicion about most boox devices sharing the same digitizer may have been correct.

Just to make sure that the input settings are actually all the same, could you run
```
adb shell getevent -lp /dev/input/event3
```
This should list out some info about the digitizer (udev stuff)

Edit: Also while I am here, this is the daemon script (ill commit it this evening as well)

```sh
: ${interval:=10}

while :; do
    if [ -n "$(adb devices -l | grep BOOX)" ]; then
        setsid -f vboox 2>&1 > /dev/null
        connected=true
    elif [ "$connected" = "true" ] && [ -z "$(adb devices -l | grep BOOX)" ]; then
        connected=false
        kill $(pidof vboox)
    fi
    sleep $interval
done
```

**Comment by DrChr** [comment]
```
$ adb shell getevent -lp /dev/input/event3
add device 1: /dev/input/event3
  name:     "onyx_emp_Wacom I2C Digitizer"
  events:
    KEY (0001): BTN_TOOL_RUBBER       BTN_TOOL_BRUSH        BTN_TOUCH             BTN_STYLUS           
                BTN_STYLUS2           0152                  0153                 
    ABS (0003): ABS_X                 : value 10007, min 0, max 20966, fuzz 0, flat 0, resolution 0
                ABS_Y                 : value 10137, min 0, max 15725, fuzz 0, flat 0, resolution 0
                ABS_PRESSURE          : value 0, min 0, max 4095, fuzz 0, flat 0, resolution 0
                ABS_DISTANCE          : value 81, min 0, max 255, fuzz 0, flat 0, resolution 0
                ABS_TILT_X            : value -24, min -63, max 63, fuzz 0, flat 0, resolution 0
                ABS_TILT_Y            : value -11, min -63, max 63, fuzz 0, flat 0, resolution 0
  input props:
    INPUT_PROP_DIRECT
```

**Comment by DrChr** [comment]
>  I think my suspicion about most boox devices sharing the same digitizer may have been correct.

Maybe good with a script (or a list of commands) for users to run to output the info you're interested in?

Especially if would like users of various types devices provide the info.
Then you can just ask them to run the script and paste the output in a particular issue.

**Comment by leath-dub** [comment]
> ```
> $ adb shell getevent -lp /dev/input/event3
> add device 1: /dev/input/event3
>   name:     "onyx_emp_Wacom I2C Digitizer"
>   events:
>     KEY (0001): BTN_TOOL_RUBBER       BTN_TOOL_BRUSH        BTN_TOUCH             BTN_STYLUS           
>                 BTN_STYLUS2           0152                  0153                 
>     ABS (0003): ABS_X                 : value 10007, min 0, max 20966, fuzz 0, flat 0, resolution 0
>                 ABS_Y                 : value 10137, min 0, max 15725, fuzz 0, flat 0, resolution 0
>                 ABS_PRESSURE          : value 0, min 0, max 4095, fuzz 0, flat 0, resolution 0
>                 ABS_DISTANCE          : value 81, min 0, max 255, fuzz 0, flat 0, resolution 0
>                 ABS_TILT_X            : value -24, min -63, max 63, fuzz 0, flat 0, resolution 0
>                 ABS_TILT_Y            : value -11, min -63, max 63, fuzz 0, flat 0, resolution 0
>   input props:
>     INPUT_PROP_DIRECT
> ```

Yep its identical.



> > I think my suspicion about most boox devices sharing the same digitizer may have been correct.
> 
> Maybe good with a script (or a list of commands) for users to run to output the info you're interested in?
> 
> Especially if would like users of various types devices provide the info. Then you can just ask them to run the script and paste the output in a particular issue.

Thats a good Idea, I'll open an issue about it.

Edit: It is here #2

**Comment by DrChr** [comment]
> Also while I am here, this is the daemon script (ill commit it this evening as well)
> 
> ```shell
> : ${interval:=10}
> 
> while :; do
>     if [ -n "$(adb devices -l | grep BOOX)" ]; then
>         setsid -f vboox 2>&1 > /dev/null
>         connected=true
>     elif [ "$connected" = "true" ] && [ -z "$(adb devices -l | grep BOOX)" ]; then
>         connected=false
>         kill $(pidof vboox)
>     fi
>     sleep $interval
> done
> ```

Some comments/changes for readability (I know, probably overkill considering... but I was bored:-):

```shell
: ${check_period_in_seconds:=10}   ## CHR-01: Suggest name change or sth to indicate unit, could just be a comment here
connected=false     # Tracks connection state to a BOOX device  ## CHR-03: Feels better to initalize it before 1st use

while :; do
    if [ -n "$(adb devices -l | grep BOOX)" ]; then
        setsid -f vboox 2>&1 > /dev/null            ## CHR-02a: Suggest add variable for the name of the binary? 
        connected=true
    elif [ "$connected" = "true" ] && [ -z "$(adb devices -l | grep BOOX)" ]; then
        connected=false
        kill $(pidof vboox)                             ## CHR-02b: Same variable here
    fi
    sleep $check_period_in_seconds
done

## CHR-04: Maybe factor out "$(adb devices -l | grep BOOX)" into a function for readability/maintainability?
## CHR-05: What if there's two BOOX devices connected...? 
```

Regarding CHR-05, I think it'd be ok to explicitly state only a single BOOX device at a time is supported. But might be good to make notes/comments in locations where this has an impact.

**Comment by leath-dub** [comment]
> > Also while I am here, this is the daemon script (ill commit it this evening as well)
> > ```shell
> > : ${interval:=10}
> > 
> > while :; do
> >     if [ -n "$(adb devices -l | grep BOOX)" ]; then
> >         setsid -f vboox 2>&1 > /dev/null
> >         connected=true
> >     elif [ "$connected" = "true" ] && [ -z "$(adb devices -l | grep BOOX)" ]; then
> >         connected=false
> >         kill $(pidof vboox)
> >     fi
> >     sleep $interval
> > done
> > ```
> 
> Some comments/changes for readability (I know, probably overkill considering... but I was bored:-):
> 
> ```shell
> : ${check_period_in_seconds:=10}   ## CHR-01: Suggest name change or sth to indicate unit, could just be a comment here
> connected=false     # Tracks connection state to a BOOX device  ## CHR-03: Feels better to initalize it before 1st use
> 
> while :; do
>     if [ -n "$(adb devices -l | grep BOOX)" ]; then
>         setsid -f vboox 2>&1 > /dev/null            ## CHR-02a: Suggest add variable for the name of the binary? 
>         connected=true
>     elif [ "$connected" = "true" ] && [ -z "$(adb devices -l | grep BOOX)" ]; then
>         connected=false
>         kill $(pidof vboox)                             ## CHR-02b: Same variable here
>     fi
>     sleep $check_period_in_seconds
> done
> 
> ## CHR-04: Maybe factor out "$(adb devices -l | grep BOOX)" into a function for readability/maintainability?
> ## CHR-05: What if there's two BOOX devices connected...? 
> ```
> 
> Regarding CHR-05, I think it'd be ok to explicitly state only a single BOOX device at a time is supported. But might be good to make notes/comments in locations where this has an impact.

Yeah thats much better. This raises another host of issues that I predict in the project, it works by parsing output from a cli tool, ideally I would not need to use `adb` tool and just directly setup in the program itself (you can see the process group has 2 members). I have only skimmed the source of that tool, realistically I might go down the path of writing an adb implementation library first.

**Comment by DrChr** [comment]
> This raises another host of issues that I predict in the project, it works by parsing output from a cli tool, ideally I would not need to use `adb` tool and just directly setup in the program itself (you can see the process group has 2 members). I have only skimmed the source of that tool, realistically I might go down the path of writing an adb implementation library first.

I think it's fine to rely on 'adb' for several reasons.
-  It's a weekend project as you said
-  I think it's risky to be to ambitious early on, it's more important to have a working prototype for e.g. exploring use cases.
-  I really think this kind of functionality ought to be provided directly by BOOX
- What should the architecture be like in the part of the digitizing system on the BOOX device? Should the user go with something likee the Lightbox app (1), or should there be a custom app (note 2)?

But before talking about e.g. architecture and solutions, perhaps it's better to figure out what you want to achieve? As  it's your project, what's _your_ goal?  (note 3) We're seriously off-topic now:-)   Not sure github issues is the best way to communicate.

(1) https://play.google.com/store/apps/details?id=ch.dissem.apps.lightbox, to provide the user with a clear canvas?
(note 2)  A custom app could e.g. add "virtual buttons" around the digitizer area.
(note 3) My wish is to be able to use my BOOX device as a digitizer input together with different apps on my Linux machine, but this needs to be described further.

**Comment by leath-dub** [comment]
> > This raises another host of issues that I predict in the project, it works by parsing output from a cli tool, ideally I would not need to use `adb` tool and just directly setup in the program itself (you can see the process group has 2 members). I have only skimmed the source of that tool, realistically I might go down the path of writing an adb implementation library first.
> 
> I think it's fine to rely on 'adb' for several reasons.
> 
> * It's a weekend project as you said
> * I think it's risky to be to ambitious early on, it's more important to have a working prototype for e.g. exploring use cases.
> * I really think this kind of functionality ought to be provided directly by BOOX
> * What should the architecture be like in the part of the digitizing system on the BOOX device? Should the user go with something likee the Lightbox app (1), or should there be a custom app (note 2)?
>
> But before talking about e.g. architecture and solutions, perhaps it's better to figure out what you want to achieve? As it's your project, what's _your_ goal? (note 3) We're seriously off-topic now:-) Not sure github issues is the best way to communicate.

I will close this issue now I made the commits there, we can chat on reddit if you like although I am partial to discord. (we can go from reddit though)

> (1) https://play.google.com/store/apps/details?id=ch.dissem.apps.lightbox, to provide the user with a clear canvas? (note 2) A custom app could e.g. add "virtual buttons" around the digitizer area. (note 3) My wish is to be able to use my BOOX device as a digitizer input together with different apps on my Linux machine, but this needs to be described further.

In terms of my goals, I am surprised it was so easy to get working but I am open for this to become a cool colobarative project (see how many really want this).

I think the virtual buttons is a cool idea. It would mean that there would need to be either 2 sources to fetch events from (the android client app and adb).
