### ISSUE TITLE
Boox Note Air 3

### ISSUE THREAD

**Issue by nwg-piotr** [leath-dub/vboox#5]
Hope to receive the device tomorrow. Is the project still alive? I'd be glad to help at testing on Air 3.

**Comment by leath-dub** [comment]
I am full time working with college so I don't have a lot of time for my open source projects, however I still use this project myself so I am still willing to help get it working on as man y devices.

**Comment by leath-dub** [comment]
I am working on a rewrite of the project on the side to be more agnostic, for time being if you just run with NoteAir2 let me know if that works. I only say the supported devices conservatively so far all the devices have been the same in terms of what i2c device they use.

**Comment by leath-dub** [comment]
The rewrite is here https://github.com/leath-dub/droidux !
